# Generated by Django 5.2.4 on 2025-07-08 16:41

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to=core.models.file_path)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('summury', models.TextField(blank=True, null=True)),
                ('highlights', models.TextField(blank=True, null=True)),
                ('transcript_file', models.FileField(blank=True, null=True, upload_to=core.models.file_path)),
                ('summury_file', models.FileField(blank=True, null=True, upload_to=core.models.file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auto_delete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
