# Generated by Django 5.2.4 on 2026-03-14 17:41

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_upload_output_delete_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='output_type',
            field=models.CharField(choices=[('transcript', 'Transcription'), ('summary', 'Summary'), ('highlights', 'Highlights'), ('audio', 'Audio')], max_length=20),
        ),
        migrations.AlterField(
            model_name='upload',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.file_path),
        ),
    ]
